// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _17: (x0,x1) => x0.get(x1),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _919: x0 => x0.headers,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1281: (x0,x1,x2) => x0.setItem(x1,x2),
      _1282: (x0,x1) => x0.removeItem(x1),
      _1283: (x0,x1) => x0.getItem(x1),
      _1284: (x0,x1,x2) => x0.open(x1,x2),
      _1285: (x0,x1) => x0.matchMedia(x1),
      _1286: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _1287: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1288: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1288(f,arguments.length,x0) }),
      _1289: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1290: (x0,x1) => x0.getElementById(x1),
      _1291: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1291(f,arguments.length,x0,x1) }),
      _1292: (x0,x1) => x0.requestVideoFrameCallback(x1),
      _1293: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1294: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1294(f,arguments.length,x0) }),
      _1295: (x0,x1) => x0.requestAnimationFrame(x1),
      _1296: (x0,x1) => x0.cancelVideoFrameCallback(x1),
      _1297: (x0,x1) => x0.cancelAnimationFrame(x1),
      _1298: () => new MediaStream(),
      _1299: x0 => x0.getVideoTracks(),
      _1300: (x0,x1) => x0.addTrack(x1),
      _1301: x0 => x0.getAudioTracks(),
      _1302: (x0,x1) => x0.append(x1),
      _1303: (x0,x1) => x0.removeAttribute(x1),
      _1304: x0 => x0.load(),
      _1305: x0 => x0.remove(),
      _1306: x0 => x0.hasChildNodes(),
      _1307: (x0,x1) => x0.appendChild(x1),
      _1313: (x0,x1) => x0.createElement(x1),
      _1319: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1320: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1320(f,arguments.length,x0,x1,x2) }),
      _1323: (x0,x1) => x0.getResponseHeader(x1),
      _1346: (x0,x1) => x0.item(x1),
      _1349: (x0,x1) => { x0.csp = x1 },
      _1350: x0 => x0.csp,
      _1351: (x0,x1) => x0.getCookieExpirationDate(x1),
      _1394: (x0,x1) => x0.createElement(x1),
      _1396: x0 => globalThis.URL.createObjectURL(x0),
      _1429: x0 => globalThis.window.eval(x0),
      _1430: (x0,x1) => x0.querySelector(x1),
      _1431: (x0,x1) => x0.getAttribute(x1),
      _1432: x0 => x0.reload(),
      _1433: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1433(f,arguments.length,x0) }),
      _1434: x0 => x0.update(),
      _1438: x0 => x0.preventDefault(),
      _1439: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1440: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1444: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1445: (x0,x1) => x0.canShare(x1),
      _1446: (x0,x1) => x0.share(x1),
      _1449: (x0,x1) => ({files: x0,text: x1}),
      _1451: x0 => ({files: x0}),
      _1453: x0 => ({text: x0}),
      _1454: x0 => x0.click(),
      _1465: (x0,x1) => globalThis.requestNotificationPermission(x0,x1),
      _1466: (x0,x1) => x0.replace(x1),
      _1467: x0 => x0.clear(),
      _1468: (x0,x1) => x0.assign(x1),
      _1469: x0 => new Event(x0),
      _1470: (x0,x1) => x0.dispatchEvent(x1),
      _1474: () => globalThis.agoraPasskey.isSupported(),
      _1475: () => globalThis.agoraPasskey.isPlatformAuthenticatorAvailable(),
      _1476: x0 => globalThis.agoraPasskey.createCredential(x0),
      _1477: x0 => globalThis.agoraPasskey.getCredential(x0),
      _1478: x0 => x0.getRegistrations(),
      _1479: x0 => x0.unregister(),
      _1480: x0 => x0.keys(),
      _1481: (x0,x1) => x0.delete(x1),
      _1482: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1482(f,arguments.length,x0) }),
      _1483: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1483(f,arguments.length,x0) }),
      _1484: (x0,x1) => x0.querySelectorAll(x1),
      _1485: (x0,x1) => x0.item(x1),
      _1486: (x0,x1) => x0.contains(x1),
      _1487: (x0,x1) => x0.add(x1),
      _1488: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1488(f,arguments.length,x0) }),
      _1489: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1489(f,arguments.length,x0) }),
      _1490: x0 => x0.decode(),
      _1491: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1492: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1493: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1493(f,arguments.length,x0) }),
      _1494: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1494(f,arguments.length,x0) }),
      _1495: x0 => x0.send(),
      _1496: () => new XMLHttpRequest(),
      _1497: (x0,x1) => x0.query(x1),
      _1498: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1498(f,arguments.length,x0) }),
      _1499: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1499(f,arguments.length,x0) }),
      _1500: (x0,x1,x2) => ({enableHighAccuracy: x0,timeout: x1,maximumAge: x2}),
      _1501: (x0,x1,x2,x3) => x0.getCurrentPosition(x1,x2,x3),
      _1508: (x0,x1) => x0.getUserMedia(x1),
      _1509: x0 => x0.stop(),
      _1517: x0 => ({type: x0}),
      _1518: (x0,x1) => new Blob(x0,x1),
      _1519: (x0,x1) => x0.item(x1),
      _1520: () => new FileReader(),
      _1522: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1523: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1523(f,arguments.length,x0) }),
      _1524: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1525: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1525(f,arguments.length,x0) }),
      _1526: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1526(f,arguments.length,x0) }),
      _1527: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1527(f,arguments.length,x0) }),
      _1528: (x0,x1) => x0.removeChild(x1),
      _1530: x0 => x0.deviceMemory,
      _1531: (x0,x1) => x0.key(x1),
      _1540: Date.now,
      _1542: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1543: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1544: () => new Error().stack,
      _1545: () => typeof dartUseDateNowForTicks !== "undefined",
      _1546: () => 1000 * performance.now(),
      _1547: () => Date.now(),
      _1548: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1549: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1550: () => new WeakMap(),
      _1551: (map, o) => map.get(o),
      _1552: (map, o, v) => map.set(o, v),
      _1553: (exn) => exn.toString(),
      _1554: (exn) => exn.stack,
      _1555: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1556: x0 => new WeakRef(x0),
      _1557: x0 => x0.deref(),
      _1564: () => globalThis.WeakRef,
      _1568: s => JSON.stringify(s),
      _1569: s => printToConsole(s),
      _1570: (o, p, r) => o.replaceAll(p, () => r),
      _1571: (o, p, r) => o.replace(p, () => r),
      _1572: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1573: s => s.toUpperCase(),
      _1574: s => s.trim(),
      _1575: s => s.trimLeft(),
      _1576: s => s.trimRight(),
      _1577: (string, times) => string.repeat(times),
      _1578: Function.prototype.call.bind(String.prototype.indexOf),
      _1579: (s, p, i) => s.lastIndexOf(p, i),
      _1580: (string, token) => string.split(token),
      _1581: Object.is,
      _1585: (o, c) => o instanceof c,
      _1586: o => Object.keys(o),
      _1588: (o,s,v) => o[s] = v,
      _1589: (o, a) => o + a,
      _1616: x0 => new Array(x0),
      _1618: x0 => x0.length,
      _1620: (x0,x1) => x0[x1],
      _1621: (x0,x1,x2) => { x0[x1] = x2 },
      _1624: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1626: x0 => new Int8Array(x0),
      _1627: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1629: x0 => new Uint8ClampedArray(x0),
      _1631: x0 => new Int16Array(x0),
      _1633: x0 => new Uint16Array(x0),
      _1635: x0 => new Int32Array(x0),
      _1637: x0 => new Uint32Array(x0),
      _1639: x0 => new Float32Array(x0),
      _1641: x0 => new Float64Array(x0),
      _1661: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1661(f,arguments.length,x0,x1) }),
      _1664: () => Symbol("jsBoxedDartObjectProperty"),
      _1665: x0 => x0.random(),
      _1666: (x0,x1) => x0.getRandomValues(x1),
      _1667: () => globalThis.crypto,
      _1668: () => globalThis.Math,
      _1681: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1682: (handle) => clearTimeout(handle),
      _1683: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1684: (handle) => clearInterval(handle),
      _1685: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1686: () => Date.now(),
      _1687: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1688: (x0,x1) => x0.exec(x1),
      _1689: (x0,x1) => x0.test(x1),
      _1690: x0 => x0.pop(),
      _1692: o => o === undefined,
      _1694: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1696: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1697: o => o instanceof RegExp,
      _1698: (l, r) => l === r,
      _1699: o => o,
      _1700: o => o,
      _1701: o => o,
      _1702: b => !!b,
      _1703: o => o.length,
      _1705: (o, i) => o[i],
      _1706: f => f.dartFunction,
      _1707: () => ({}),
      _1708: () => [],
      _1710: () => globalThis,
      _1711: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1712: (o, p) => p in o,
      _1713: (o, p) => o[p],
      _1714: (o, p, v) => o[p] = v,
      _1715: (o, m, a) => o[m].apply(o, a),
      _1717: o => String(o),
      _1718: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1719: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1719(f,arguments.length,x0) }),
      _1720: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1720(f,arguments.length,x0,x1) }),
      _1721: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1722: o => [o],
      _1723: (o0, o1) => [o0, o1],
      _1724: (o0, o1, o2) => [o0, o1, o2],
      _1725: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1726: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1727: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1730: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1731: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1732: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1733: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1734: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1735: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1736: x0 => new ArrayBuffer(x0),
      _1737: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1739: x0 => x0.index,
      _1740: x0 => x0.groups,
      _1741: x0 => x0.flags,
      _1742: x0 => x0.multiline,
      _1743: x0 => x0.ignoreCase,
      _1744: x0 => x0.unicode,
      _1745: x0 => x0.dotAll,
      _1746: (x0,x1) => { x0.lastIndex = x1 },
      _1747: (o, p) => p in o,
      _1748: (o, p) => o[p],
      _1749: (o, p, v) => o[p] = v,
      _1758: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1758(f,arguments.length,x0) }),
      _1759: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1759(f,arguments.length,x0) }),
      _1760: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1760(f,arguments.length,x0) }),
      _1761: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1761(f,arguments.length,x0) }),
      _1762: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1762(f,arguments.length,x0) }),
      _1763: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1763(f,arguments.length,x0) }),
      _1764: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1764(f,arguments.length,x0) }),
      _1765: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1765(f,arguments.length,x0) }),
      _1766: x0 => x0.close(),
      _1768: (x0,x1) => x0.createOffer(x1),
      _1769: (x0,x1) => x0.createAnswer(x1),
      _1772: (x0,x1) => ({type: x0,sdp: x1}),
      _1773: (x0,x1) => x0.setLocalDescription(x1),
      _1774: (x0,x1) => ({type: x0,sdp: x1}),
      _1775: (x0,x1) => x0.setRemoteDescription(x1),
      _1776: (x0,x1,x2) => ({candidate: x0,sdpMid: x1,sdpMLineIndex: x2}),
      _1777: (x0,x1) => x0.addIceCandidate(x1),
      _1785: x0 => x0.restartIce(),
      _1787: (x0,x1,x2) => x0.addTrack(x1,x2),
      _1797: x0 => new RTCPeerConnection(x0),
      _1811: (x0,x1) => ({video: x0,audio: x1}),
      _1823: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1823(f,arguments.length,x0) }),
      _1824: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1824(f,arguments.length,x0) }),
      _1825: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1825(f,arguments.length,x0) }),
      _4443: () => new XMLHttpRequest(),
      _4444: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _4446: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _4447: (x0,x1) => x0.send(x1),
      _4448: x0 => x0.send(),
      _4450: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4450(f,arguments.length,x0) }),
      _4451: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4451(f,arguments.length,x0) }),
      _4468: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4468(f,arguments.length,x0) }),
      _4469: (x0,x1,x2) => x0.postMessage(x1,x2),
      _4470: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4470(f,arguments.length,x0) }),
      _4471: () => new AbortController(),
      _4472: x0 => x0.abort(),
      _4473: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _4474: (x0,x1) => globalThis.fetch(x0,x1),
      _4475: (x0,x1) => x0.get(x1),
      _4476: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._4476(f,arguments.length,x0,x1,x2) }),
      _4477: (x0,x1) => x0.forEach(x1),
      _4478: x0 => x0.getReader(),
      _4479: x0 => x0.cancel(),
      _4480: x0 => x0.read(),
      _4487: () => globalThis.window.flutter_inappwebview,
      _4491: (x0,x1) => { x0.nativeCommunication = x1 },
      _4495: o => o instanceof Array,
      _4496: (a, i) => a.push(i),
      _4497: (a, i) => a.splice(i, 1)[0],
      _4499: (a, l) => a.length = l,
      _4500: a => a.pop(),
      _4501: (a, i) => a.splice(i, 1),
      _4502: (a, s) => a.join(s),
      _4503: (a, s, e) => a.slice(s, e),
      _4505: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _4506: a => a.length,
      _4507: (a, l) => a.length = l,
      _4508: (a, i) => a[i],
      _4509: (a, i, v) => a[i] = v,
      _4511: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _4512: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _4514: o => o instanceof Uint8Array,
      _4515: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _4516: o => o instanceof Int8Array,
      _4517: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _4518: o => o instanceof Uint8ClampedArray,
      _4519: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _4520: o => o instanceof Uint16Array,
      _4521: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _4522: o => o instanceof Int16Array,
      _4523: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _4524: o => o instanceof Uint32Array,
      _4525: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _4526: o => o instanceof Int32Array,
      _4527: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _4529: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _4530: o => o instanceof Float32Array,
      _4531: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _4532: o => o instanceof Float64Array,
      _4533: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _4534: (t, s) => t.set(s),
      _4535: l => new DataView(new ArrayBuffer(l)),
      _4536: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _4538: o => o.buffer,
      _4539: o => o.byteOffset,
      _4540: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _4541: (b, o) => new DataView(b, o),
      _4542: (b, o, l) => new DataView(b, o, l),
      _4543: Function.prototype.call.bind(DataView.prototype.getUint8),
      _4544: Function.prototype.call.bind(DataView.prototype.setUint8),
      _4545: Function.prototype.call.bind(DataView.prototype.getInt8),
      _4546: Function.prototype.call.bind(DataView.prototype.setInt8),
      _4547: Function.prototype.call.bind(DataView.prototype.getUint16),
      _4548: Function.prototype.call.bind(DataView.prototype.setUint16),
      _4549: Function.prototype.call.bind(DataView.prototype.getInt16),
      _4550: Function.prototype.call.bind(DataView.prototype.setInt16),
      _4551: Function.prototype.call.bind(DataView.prototype.getUint32),
      _4552: Function.prototype.call.bind(DataView.prototype.setUint32),
      _4553: Function.prototype.call.bind(DataView.prototype.getInt32),
      _4554: Function.prototype.call.bind(DataView.prototype.setInt32),
      _4557: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _4558: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _4559: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _4560: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _4561: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _4562: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _4563: Function.prototype.call.bind(Number.prototype.toString),
      _4564: Function.prototype.call.bind(BigInt.prototype.toString),
      _4565: Function.prototype.call.bind(Number.prototype.toString),
      _4566: (d, digits) => d.toFixed(digits),
      _4663: () => globalThis.document,
      _4669: (x0,x1) => { x0.height = x1 },
      _4671: (x0,x1) => { x0.width = x1 },
      _4673: (x0,x1) => { x0.pointerEvents = x1 },
      _4682: x0 => x0.style,
      _4685: x0 => x0.src,
      _4686: (x0,x1) => { x0.src = x1 },
      _4687: x0 => x0.naturalWidth,
      _4688: x0 => x0.naturalHeight,
      _4704: x0 => x0.status,
      _4705: (x0,x1) => { x0.responseType = x1 },
      _4707: x0 => x0.response,
      _4754: x0 => x0.status,
      _4759: x0 => x0.responseText,
      _4818: (x0,x1) => { x0.draggable = x1 },
      _4834: x0 => x0.style,
      _5310: x0 => x0.src,
      _5311: (x0,x1) => { x0.src = x1 },
      _5313: (x0,x1) => { x0.srcdoc = x1 },
      _5314: x0 => x0.name,
      _5315: (x0,x1) => { x0.name = x1 },
      _5316: x0 => x0.sandbox,
      _5317: x0 => x0.allow,
      _5318: (x0,x1) => { x0.allow = x1 },
      _5319: x0 => x0.allowFullscreen,
      _5320: (x0,x1) => { x0.allowFullscreen = x1 },
      _5325: x0 => x0.referrerPolicy,
      _5326: (x0,x1) => { x0.referrerPolicy = x1 },
      _5329: x0 => x0.contentDocument,
      _5403: (x0,x1) => { x0.width = x1 },
      _5405: (x0,x1) => { x0.height = x1 },
      _5406: x0 => x0.videoWidth,
      _5407: x0 => x0.videoHeight,
      _5438: x0 => x0.error,
      _5442: (x0,x1) => { x0.srcObject = x1 },
      _5450: x0 => x0.readyState,
      _5452: x0 => x0.currentTime,
      _5466: (x0,x1) => { x0.autoplay = x1 },
      _5470: (x0,x1) => { x0.controls = x1 },
      _5474: (x0,x1) => { x0.muted = x1 },
      _5489: x0 => x0.code,
      _5490: x0 => x0.message,
      _5761: (x0,x1) => { x0.accept = x1 },
      _5775: x0 => x0.files,
      _5801: (x0,x1) => { x0.multiple = x1 },
      _5819: (x0,x1) => { x0.type = x1 },
      _6536: () => globalThis.window,
      _6573: x0 => x0.document,
      _6576: x0 => x0.location,
      _6577: x0 => x0.history,
      _6595: x0 => x0.navigator,
      _6600: x0 => x0.visualViewport,
      _6856: x0 => x0.caches,
      _6858: x0 => x0.sessionStorage,
      _6859: x0 => x0.localStorage,
      _6864: x0 => x0.href,
      _6865: (x0,x1) => { x0.href = x1 },
      _6866: x0 => x0.origin,
      _6867: x0 => x0.protocol,
      _6871: x0 => x0.hostname,
      _6873: x0 => x0.port,
      _6875: x0 => x0.pathname,
      _6912: x0 => x0.message,
      _6957: x0 => x0.geolocation,
      _6960: x0 => x0.mediaDevices,
      _6962: x0 => x0.permissions,
      _6963: x0 => x0.maxTouchPoints,
      _6966: x0 => x0.serviceWorker,
      _6970: x0 => x0.appCodeName,
      _6971: x0 => x0.appName,
      _6972: x0 => x0.appVersion,
      _6973: x0 => x0.platform,
      _6974: x0 => x0.product,
      _6975: x0 => x0.productSub,
      _6976: x0 => x0.userAgent,
      _6977: x0 => x0.vendor,
      _6978: x0 => x0.vendorSub,
      _6980: x0 => x0.language,
      _6981: x0 => x0.languages,
      _6982: x0 => x0.onLine,
      _6987: x0 => x0.hardwareConcurrency,
      _7026: x0 => x0.data,
      _7027: x0 => x0.origin,
      _7029: x0 => x0.source,
      _7181: x0 => x0.length,
      _7470: x0 => x0.signalingState,
      _7471: x0 => x0.iceGatheringState,
      _7472: x0 => x0.iceConnectionState,
      _7473: x0 => x0.connectionState,
      _7486: (x0,x1) => { x0.onicegatheringstatechange = x1 },
      _7500: x0 => x0.type,
      _7502: x0 => x0.sdp,
      _7510: x0 => x0.candidate,
      _7511: x0 => x0.sdpMid,
      _7512: x0 => x0.sdpMLineIndex,
      _7534: x0 => x0.candidate,
      _7570: x0 => x0.track,
      _7703: x0 => x0.receiver,
      _7704: x0 => x0.track,
      _7705: x0 => x0.streams,
      _7706: x0 => x0.transceiver,
      _9101: x0 => x0.signal,
      _9110: x0 => x0.length,
      _9154: x0 => x0.baseURI,
      _9160: x0 => x0.firstChild,
      _9171: () => globalThis.document,
      _9230: x0 => x0.documentElement,
      _9251: x0 => x0.body,
      _9581: x0 => x0.id,
      _9582: (x0,x1) => { x0.id = x1 },
      _9585: x0 => x0.classList,
      _9596: x0 => x0.scrollHeight,
      _9609: x0 => x0.children,
      _9810: x0 => x0.length,
      _10925: x0 => x0.value,
      _10927: x0 => x0.done,
      _11106: x0 => x0.size,
      _11107: x0 => x0.type,
      _11113: x0 => x0.name,
      _11119: x0 => x0.length,
      _11124: x0 => x0.result,
      _11200: x0 => x0.scope,
      _11210: x0 => x0.ready,
      _11613: x0 => x0.url,
      _11615: x0 => x0.status,
      _11617: x0 => x0.statusText,
      _11618: x0 => x0.headers,
      _11619: x0 => x0.body,
      _11901: x0 => x0.matches,
      _12006: x0 => x0.state,
      _12403: x0 => x0.id,
      _12410: x0 => x0.kind,
      _12411: x0 => x0.id,
      _12412: x0 => x0.label,
      _12413: x0 => x0.enabled,
      _12414: (x0,x1) => { x0.enabled = x1 },
      _12415: x0 => x0.muted,
      _13309: x0 => x0.coords,
      _13310: x0 => x0.timestamp,
      _13312: x0 => x0.accuracy,
      _13313: x0 => x0.latitude,
      _13314: x0 => x0.longitude,
      _13315: x0 => x0.altitude,
      _13316: x0 => x0.altitudeAccuracy,
      _13317: x0 => x0.heading,
      _13318: x0 => x0.speed,
      _13319: x0 => x0.code,
      _13320: x0 => x0.message,
      _13728: (x0,x1) => { x0.border = x1 },
      _14006: (x0,x1) => { x0.display = x1 },
      _14170: (x0,x1) => { x0.height = x1 },
      _14226: (x0,x1) => { x0.left = x1 },
      _14364: (x0,x1) => { x0.objectFit = x1 },
      _14382: (x0,x1) => { x0.opacity = x1 },
      _14398: (x0,x1) => { x0.overflow = x1 },
      _14494: (x0,x1) => { x0.pointerEvents = x1 },
      _14496: (x0,x1) => { x0.position = x1 },
      _14788: (x0,x1) => { x0.top = x1 },
      _14834: (x0,x1) => { x0.visibility = x1 },
      _14860: (x0,x1) => { x0.width = x1 },
      _15228: x0 => x0.name,
      _15229: x0 => x0.message,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
